Fixed issue #59 OpenAPI(Swagger) For API
thenewboston-developers/Bank pull request #127
Opened 2021-01-11 10:18 UTC by adewolejosh

- used a module drf_yasg to setup an OpenAPI(Swagger) to solve issue #59

2021-01-11 14:16 UTC, adewolejosh commented
closes  #59

Issue fixed, all checks passed and can be reviewed to merge.

2021-01-11 14:38 UTC, vosi requested changes
also, please run scripts/compile_requirements.sh to generate requirements

2021-01-11 14:38 UTC, vosi commented on requirements/base.in
> +flake8==3.8.4
no need to have flake8 listed separately

2021-01-11 14:38 UTC, vosi commented on requirements/base.in
> +thenewboston==0.0.24
please, use the latest version of the package

2021-01-11 14:39 UTC, vosi commented on requirements/base.in
> +flake8==3.8.4
it is part of thenewboston package

2021-01-11 16:17 UTC, adewolejosh commented
Hi @vosi I'm having some issues on my personal computer as regards the installation of the latest version of thenewboston, I don't know if it's a general issue. 

I'll be posting some pictures of the error below. The first picture is when I try to install thenewboston using pip
![error](https://user-images.githubusercontent.com/39972589/104206819-494eda80-5430-11eb-9fdb-685ddb407313.png)

while the second picture is when I try to run script/compile_requirements.sh whilst using the latest version of thenewboston package in bash.in

![error2](https://user-images.githubusercontent.com/39972589/104207980-c417f580-5430-11eb-847d-5308ae64e8a1.png)


and I think, it is the cause for my failing tests. Anyway in which you can help?

2021-01-11 17:52 UTC, adewolejosh commented
@vosi I believe I've made the requested changes. kindly review. Just by the way there should be a very direct message to all new contributors to use Python Versions greater than 3.7 as it is needed to run thenewboston package successfully(this was the problem hindering me from using thenewboston latest package)

2021-01-11 17:59 UTC, vosi commented
> @vosi I believe I've made the requested changes. kindly review. Just by the way there should be a very direct message to all new contributors to use Python Versions greater than 3.7 as it is needed to run thenewboston package successfully(this was the problem hindering me from using thenewboston latest package)

https://pypi.org/project/thenewboston/ 

```
 Requires: Python >=3.7 
```

2021-01-30 18:04 UTC, adewolejosh commented
Hi @vosi, seeing there was an upgrade in thenewboston package, I just upgraded mine to the latest. Kindly Review, Thanks!

2021-02-13 22:30 UTC, buckyroberts commented
@danpadev can you resolve these conflicts and then review?

2021-02-14 10:34 UTC, vosi approved these changes

2021-02-14 21:58 UTC, buckyroberts commented
@dmugtasimov after the [Upgrade requirements](https://github.com/thenewboston-developers/thenewboston-python/issues/48) ticket can you fix these conflicts as well?

2021-02-14 23:10 UTC, merged